import { PropTypes } from 'react';
var T = PropTypes;
  
var contractPropTypes = {
  holidays: T.array,
  hourly_rate: T.string,
  payment_frequency: T.string,
  payday: T.string,
  address: T.string,
  start_date: T.datetime,
  overtime_rate: T.string,
  overtime_holidays: T.array,
  overtime_notice_length: T.string,
  parental_leave_notice_length: T.string,
  parental_leave_length: T.string,
  parental_leave_paid: T.bool,
  parental_leave_paid_note: T.string,
  reduced_hours_reg_wage: T.string,
  cancelled_day_paid: T.bool,
  bad_weather_day_paid: T.bool,
  room_provided: T.bool,
  room_size: T.number,
  room_num_beds: T.number,
  room_num_people: T.number,
  room_working_heat: T.bool,
  room_heat_controlled: T.bool,
  room_clean: T.bool,
  room_entry_notice_length: T.string,
  room_entry_emergency_repairs: T.bool,
  room_entry_specific_repairs: T.bool,
  room_entry_other: T.bool,
  board_provided: T.bool,
  board_provided_house_food: T.bool,
  board_provided_free_food: T.bool,
  board_provided_bring_own_food: T.bool,
  board_provided_paid_food_agreed: T.bool,
  board_provided_paid_food_agreed_notes: T.string,
  benefits_paid_health: T.bool,
  benefits_transportation: T.bool,
  benefits_notes: T.string,
  workers_comp_insurance_company: T.string,
  workers_comp_insurance_policy: T.string,
  deduction_state_income_tax: T.string,
  deduction_federal_tax: T.string,
  deduction_health_insurance: T.string,
  deduction_food: T.string,
  deduction_lodging: T.string,
  deduction_other: T.string,
  evaluation_frequency: T.string,
  complaint_handling_process: T.string,
  disclose_private_info_permitted: T.bool,
  share_family_pics_permitted: T.bool,
  fam_can_restrict_private_comm: T.bool,
  fam_can_surveil: T.bool,
  fam_can_take_away_personal_docs: T.bool,
  fam_can_forced_service: T.bool,
  fam_can_forced_service_notes: T.string,
  termination_notice_length: T.string,
  termination_severance_length: T.string,
  termination_accom_eviction_notice_length: T.string,
  termination_paid_if_evicted_early: T.bool,
  termination_grounds: T.string
};

module.exports = {contractPropTypes};