#!/bin/bash

set -e

git checkout -b gh-pages
BUILD_PRERELEASE='true' $(npm bin)/webpack -p --color --display-error-details --config webpack.config.js --bail 2>&1
git add .
git commit -am 'release build'
git push origin :gh-pages
git subtree push --prefix public origin gh-pages
git checkout master
git branch -D gh-pages
git push origin master

